
GET http://localhost:3000/api/guitars

###
GET http://localhost:3000/api/guitars/1

###
POST http://localhost:3000/api/guitars
Content-Type: application/json

{
    "brand": "Gretsch",
    "model": "Nashville 6120",
    "color": "Orange"
}

###
PUT   http://localhost:3000/api/guitars/1
Content-Type: application/json

{
    "brand": "Fender",
    "model": "Telecaster 62",
    "color": "White",
    "id": 1
}

###
DELETE  http://localhost:3000/api/guitars/1
Content-Type: application/json